# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientTrading/SpdrParentBrokerSummary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spiderrock_common_pb2 as spiderrock__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+ClientTrading/SpdrParentBrokerSummary.proto\x12\x13spiderrock.protobuf\x1a\x17spiderrock_common.proto\"\x9a\x06\n\x17SpdrParentBrokerSummary\x12\x33\n\x05_meta\x18\x01 \x01(\x0b\x32$.spiderrock.protobuf.MessageMetadata\x12?\n\x04pkey\x18\x02 \x01(\x0b\x32\x31.spiderrock.protobuf.SpdrParentBrokerSummary.PKey\x12\x12\n\nnum_orders\x18g \x01(\x05\x12\x13\n\x0bnum_brokers\x18j \x01(\x05\x12\x14\n\x0cnum_sec_keys\x18m \x01(\x05\x12\x16\n\x0enum_underliers\x18p \x01(\x05\x12\x16\n\x0esum_order_size\x18s \x01(\x05\x12\x1a\n\x12sum_sweep_mkt_size\x18v \x01(\x05\x12\x1a\n\x12sum_sweep_fill_qty\x18y \x01(\x05\x12\x1a\n\x12sum_active_seconds\x18| \x01(\x02\x12\x1b\n\x13sum_working_seconds\x18\x7f \x01(\x02\x12\x19\n\x10num_child_orders\x18\x82\x01 \x01(\x05\x12\x15\n\x0c\x63um_fill_qty\x18\x85\x01 \x01(\x05\x12\x15\n\x0csum_vwap_qty\x18\x88\x01 \x01(\x05\x12\x16\n\rsum_vwap_pn_l\x18\x8b\x01 \x01(\x02\x1a\xc7\x02\n\x04PKey\x12\r\n\x05\x61\x63\x63nt\x18\n \x01(\t\x12\x32\n\x08sec_type\x18\x0b \x01(\x0e\x32 .spiderrock.protobuf.SpdrKeyType\x12\x32\n\nticker_src\x18\x0c \x01(\x0e\x32\x1e.spiderrock.protobuf.TickerSrc\x12\x34\n\x0bspdr_source\x18\r \x01(\x0e\x32\x1f.spiderrock.protobuf.SpdrSource\x12G\n\x15parent_order_handling\x18\x0e \x01(\x0e\x32(.spiderrock.protobuf.ParentOrderHandling\x12\x34\n\x0etrading_period\x18\x0f \x01(\x0b\x32\x1c.spiderrock.protobuf.DateKey\x12\x13\n\x0b\x63lient_firm\x18\x10 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientTrading.SpdrParentBrokerSummary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SPDRPARENTBROKERSUMMARY']._serialized_start=94
  _globals['_SPDRPARENTBROKERSUMMARY']._serialized_end=888
  _globals['_SPDRPARENTBROKERSUMMARY_PKEY']._serialized_start=561
  _globals['_SPDRPARENTBROKERSUMMARY_PKEY']._serialized_end=888
# @@protoc_insertion_point(module_scope)
