// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protobuf/RiskCalc/OptionItemDef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spiderrock.Protobuf {

  /// <summary>Holder for reflection information generated from Protobuf/RiskCalc/OptionItemDef.proto</summary>
  public static partial class OptionItemDefReflection {

    #region Descriptor
    /// <summary>File descriptor for Protobuf/RiskCalc/OptionItemDef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionItemDefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVQcm90b2J1Zi9SaXNrQ2FsYy9PcHRpb25JdGVtRGVmLnByb3RvEhNzcGlk",
            "ZXJyb2NrLnByb3RvYnVmGhdzcGlkZXJyb2NrX2NvbW1vbi5wcm90bxofZ29v",
            "Z2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byL/BgoNT3B0aW9uSXRlbURl",
            "ZhIzCgVfbWV0YRgBIAEoCzIkLnNwaWRlcnJvY2sucHJvdG9idWYuTWVzc2Fn",
            "ZU1ldGFkYXRhEjUKBHBrZXkYAiABKAsyJy5zcGlkZXJyb2NrLnByb3RvYnVm",
            "Lk9wdGlvbkl0ZW1EZWYuUEtleRIyCgdleF90eXBlGGQgASgOMiEuc3BpZGVy",
            "cm9jay5wcm90b2J1Zi5FeGVyY2lzZVR5cGUSMgoHZXhfdGltZRhlIAEoDjIh",
            "LnNwaWRlcnJvY2sucHJvdG9idWYuRXhlcmNpc2VUaW1lEjsKEGhvbGlkYXlf",
            "Y2FsZW5kYXIYcyABKA4yIS5zcGlkZXJyb2NrLnByb3RvYnVmLkNhbGVuZGFy",
            "Q29kZRI0Cgt0aW1lX21ldHJpYxhmIAEoDjIfLnNwaWRlcnJvY2sucHJvdG9i",
            "dWYuVGltZU1ldHJpYxI2CgpwcmljZV90eXBlGGcgASgOMiIuc3BpZGVycm9j",
            "ay5wcm90b2J1Zi5DYWxjUHJpY2VUeXBlEjYKCm1vZGVsX3R5cGUYaCABKA4y",
            "Ii5zcGlkZXJyb2NrLnByb3RvYnVmLkNhbGNNb2RlbFR5cGUSLgoKaW5jX2dy",
            "ZWVrcxhpIAEoDjIaLnNwaWRlcnJvY2sucHJvdG9idWYuWWVzTm8SCwoDdm9s",
            "GGogASgBEg0KBXVfcHJjGGsgASgBEg0KBXllYXJzGGwgASgBEgwKBHNkaXYY",
            "bSABKAESDAoEcmF0ZRhuIAEoARItCgl0aW1lc3RhbXAYciABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wEk4KEWRpc2NyZXRlX2RpdmlkZW5kGG8g",
            "AygLMjMuc3BpZGVycm9jay5wcm90b2J1Zi5PcHRpb25JdGVtRGVmLkRpc2Ny",
            "ZXRlRGl2aWRlbmQacwoEUEtleRIsCgRva2V5GAogASgLMh4uc3BpZGVycm9j",
            "ay5wcm90b2J1Zi5PcHRpb25LZXkSEwoLb2tleV9udW1iZXIYDSABKAUSFQoN",
            "YmFza2V0X251bWJlchgLIAEoAxIRCgl1c2VyX25hbWUYDCABKAkaTAoQRGlz",
            "Y3JldGVEaXZpZGVuZBIoCgRkYXRlGHAgASgLMhouZ29vZ2xlLnByb3RvYnVm",
            "LlRpbWVzdGFtcBIOCgZhbW91bnQYcSABKAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Spiderrock.Protobuf.SpiderrockCommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spiderrock.Protobuf.OptionItemDef), global::Spiderrock.Protobuf.OptionItemDef.Parser, new[]{ "Meta", "Pkey", "ExType", "ExTime", "HolidayCalendar", "TimeMetric", "PriceType", "ModelType", "IncGreeks", "Vol", "UPrc", "Years", "Sdiv", "Rate", "Timestamp", "DiscreteDividend" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Spiderrock.Protobuf.OptionItemDef.Types.PKey), global::Spiderrock.Protobuf.OptionItemDef.Types.PKey.Parser, new[]{ "Okey", "OkeyNumber", "BasketNumber", "UserName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend), global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend.Parser, new[]{ "Date", "Amount" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OptionItemDef : pb::IMessage<OptionItemDef>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OptionItemDef> _parser = new pb::MessageParser<OptionItemDef>(() => new OptionItemDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OptionItemDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spiderrock.Protobuf.OptionItemDefReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptionItemDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptionItemDef(OptionItemDef other) : this() {
      Meta_ = other.Meta_ != null ? other.Meta_.Clone() : null;
      pkey_ = other.pkey_ != null ? other.pkey_.Clone() : null;
      exType_ = other.exType_;
      exTime_ = other.exTime_;
      holidayCalendar_ = other.holidayCalendar_;
      timeMetric_ = other.timeMetric_;
      priceType_ = other.priceType_;
      modelType_ = other.modelType_;
      incGreeks_ = other.incGreeks_;
      vol_ = other.vol_;
      uPrc_ = other.uPrc_;
      years_ = other.years_;
      sdiv_ = other.sdiv_;
      rate_ = other.rate_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      discreteDividend_ = other.discreteDividend_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptionItemDef Clone() {
      return new OptionItemDef(this);
    }

    /// <summary>Field number for the "_meta" field.</summary>
    public const int MetaFieldNumber = 1;
    private global::Spiderrock.Protobuf.MessageMetadata Meta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.MessageMetadata Meta {
      get { return Meta_; }
      set {
        Meta_ = value;
      }
    }

    /// <summary>Field number for the "pkey" field.</summary>
    public const int PkeyFieldNumber = 2;
    private global::Spiderrock.Protobuf.OptionItemDef.Types.PKey pkey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.OptionItemDef.Types.PKey Pkey {
      get { return pkey_; }
      set {
        pkey_ = value;
      }
    }

    /// <summary>Field number for the "ex_type" field.</summary>
    public const int ExTypeFieldNumber = 100;
    private global::Spiderrock.Protobuf.ExerciseType exType_ = global::Spiderrock.Protobuf.ExerciseType.Unspecified;
    /// <summary>
    /// exercise type of the option (American or European) (default: root definition)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.ExerciseType ExType {
      get { return exType_; }
      set {
        exType_ = value;
      }
    }

    /// <summary>Field number for the "ex_time" field.</summary>
    public const int ExTimeFieldNumber = 101;
    private global::Spiderrock.Protobuf.ExerciseTime exTime_ = global::Spiderrock.Protobuf.ExerciseTime.Unspecified;
    /// <summary>
    /// exercise time (AM or PM) (default: root definition)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.ExerciseTime ExTime {
      get { return exTime_; }
      set {
        exTime_ = value;
      }
    }

    /// <summary>Field number for the "holiday_calendar" field.</summary>
    public const int HolidayCalendarFieldNumber = 115;
    private global::Spiderrock.Protobuf.CalendarCode holidayCalendar_ = global::Spiderrock.Protobuf.CalendarCode.Unspecified;
    /// <summary>
    /// holiday calendar code (eg. NYSE)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.CalendarCode HolidayCalendar {
      get { return holidayCalendar_; }
      set {
        holidayCalendar_ = value;
      }
    }

    /// <summary>Field number for the "time_metric" field.</summary>
    public const int TimeMetricFieldNumber = 102;
    private global::Spiderrock.Protobuf.TimeMetric timeMetric_ = global::Spiderrock.Protobuf.TimeMetric.Unspecified;
    /// <summary>
    /// time metric (VT70, Y252, Y365, etc.) (default: root definition)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.TimeMetric TimeMetric {
      get { return timeMetric_; }
      set {
        timeMetric_ = value;
      }
    }

    /// <summary>Field number for the "price_type" field.</summary>
    public const int PriceTypeFieldNumber = 103;
    private global::Spiderrock.Protobuf.CalcPriceType priceType_ = global::Spiderrock.Protobuf.CalcPriceType.Unspecified;
    /// <summary>
    /// Equity (spot price) or Future (fwd price) conventions (default: root definition)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.CalcPriceType PriceType {
      get { return priceType_; }
      set {
        priceType_ = value;
      }
    }

    /// <summary>Field number for the "model_type" field.</summary>
    public const int ModelTypeFieldNumber = 104;
    private global::Spiderrock.Protobuf.CalcModelType modelType_ = global::Spiderrock.Protobuf.CalcModelType.Unspecified;
    /// <summary>
    /// (default: root definition)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.CalcModelType ModelType {
      get { return modelType_; }
      set {
        modelType_ = value;
      }
    }

    /// <summary>Field number for the "inc_greeks" field.</summary>
    public const int IncGreeksFieldNumber = 105;
    private global::Spiderrock.Protobuf.YesNo incGreeks_ = global::Spiderrock.Protobuf.YesNo.Unspecified;
    /// <summary>
    /// default (No)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Spiderrock.Protobuf.YesNo IncGreeks {
      get { return incGreeks_; }
      set {
        incGreeks_ = value;
      }
    }

    /// <summary>Field number for the "vol" field.</summary>
    public const int VolFieldNumber = 106;
    private double vol_;
    /// <summary>
    /// volatility (default: SR surface volatility)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Vol {
      get { return vol_; }
      set {
        vol_ = value;
      }
    }

    /// <summary>Field number for the "u_prc" field.</summary>
    public const int UPrcFieldNumber = 107;
    private double uPrc_;
    /// <summary>
    /// underlying price (default: SR live uPrc)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UPrc {
      get { return uPrc_; }
      set {
        uPrc_ = value;
      }
    }

    /// <summary>Field number for the "years" field.</summary>
    public const int YearsFieldNumber = 108;
    private double years_;
    /// <summary>
    /// years-to-expiration (default: SR volatility time value)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Years {
      get { return years_; }
      set {
        years_ = value;
      }
    }

    /// <summary>Field number for the "sdiv" field.</summary>
    public const int SdivFieldNumber = 109;
    private double sdiv_;
    /// <summary>
    /// continuous stock dividend using for pricing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Sdiv {
      get { return sdiv_; }
      set {
        sdiv_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 110;
    private double rate_;
    /// <summary>
    /// discount rate used for pricing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 114;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "discrete_dividend" field.</summary>
    public const int DiscreteDividendFieldNumber = 111;
    private static readonly pb::FieldCodec<global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend> _repeated_discreteDividend_codec
        = pb::FieldCodec.ForMessage(890, global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend.Parser);
    private readonly pbc::RepeatedField<global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend> discreteDividend_ = new pbc::RepeatedField<global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Spiderrock.Protobuf.OptionItemDef.Types.DiscreteDividend> DiscreteDividend {
      get { return discreteDividend_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OptionItemDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OptionItemDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Meta, other.Meta)) return false;
      if (!object.Equals(Pkey, other.Pkey)) return false;
      if (ExType != other.ExType) return false;
      if (ExTime != other.ExTime) return false;
      if (HolidayCalendar != other.HolidayCalendar) return false;
      if (TimeMetric != other.TimeMetric) return false;
      if (PriceType != other.PriceType) return false;
      if (ModelType != other.ModelType) return false;
      if (IncGreeks != other.IncGreeks) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Vol, other.Vol)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UPrc, other.UPrc)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Years, other.Years)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Sdiv, other.Sdiv)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Rate, other.Rate)) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if(!discreteDividend_.Equals(other.discreteDividend_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Meta_ != null) hash ^= Meta.GetHashCode();
      if (pkey_ != null) hash ^= Pkey.GetHashCode();
      if (ExType != global::Spiderrock.Protobuf.ExerciseType.Unspecified) hash ^= ExType.GetHashCode();
      if (ExTime != global::Spiderrock.Protobuf.ExerciseTime.Unspecified) hash ^= ExTime.GetHashCode();
      if (HolidayCalendar != global::Spiderrock.Protobuf.CalendarCode.Unspecified) hash ^= HolidayCalendar.GetHashCode();
      if (TimeMetric != global::Spiderrock.Protobuf.TimeMetric.Unspecified) hash ^= TimeMetric.GetHashCode();
      if (PriceType != global::Spiderrock.Protobuf.CalcPriceType.Unspecified) hash ^= PriceType.GetHashCode();
      if (ModelType != global::Spiderrock.Protobuf.CalcModelType.Unspecified) hash ^= ModelType.GetHashCode();
      if (IncGreeks != global::Spiderrock.Protobuf.YesNo.Unspecified) hash ^= IncGreeks.GetHashCode();
      if (Vol != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Vol);
      if (UPrc != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UPrc);
      if (Years != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Years);
      if (Sdiv != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Sdiv);
      if (Rate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Rate);
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= discreteDividend_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Meta_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Meta);
      }
      if (pkey_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pkey);
      }
      if (ExType != global::Spiderrock.Protobuf.ExerciseType.Unspecified) {
        output.WriteRawTag(160, 6);
        output.WriteEnum((int) ExType);
      }
      if (ExTime != global::Spiderrock.Protobuf.ExerciseTime.Unspecified) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ExTime);
      }
      if (TimeMetric != global::Spiderrock.Protobuf.TimeMetric.Unspecified) {
        output.WriteRawTag(176, 6);
        output.WriteEnum((int) TimeMetric);
      }
      if (PriceType != global::Spiderrock.Protobuf.CalcPriceType.Unspecified) {
        output.WriteRawTag(184, 6);
        output.WriteEnum((int) PriceType);
      }
      if (ModelType != global::Spiderrock.Protobuf.CalcModelType.Unspecified) {
        output.WriteRawTag(192, 6);
        output.WriteEnum((int) ModelType);
      }
      if (IncGreeks != global::Spiderrock.Protobuf.YesNo.Unspecified) {
        output.WriteRawTag(200, 6);
        output.WriteEnum((int) IncGreeks);
      }
      if (Vol != 0D) {
        output.WriteRawTag(209, 6);
        output.WriteDouble(Vol);
      }
      if (UPrc != 0D) {
        output.WriteRawTag(217, 6);
        output.WriteDouble(UPrc);
      }
      if (Years != 0D) {
        output.WriteRawTag(225, 6);
        output.WriteDouble(Years);
      }
      if (Sdiv != 0D) {
        output.WriteRawTag(233, 6);
        output.WriteDouble(Sdiv);
      }
      if (Rate != 0D) {
        output.WriteRawTag(241, 6);
        output.WriteDouble(Rate);
      }
      discreteDividend_.WriteTo(output, _repeated_discreteDividend_codec);
      if (timestamp_ != null) {
        output.WriteRawTag(146, 7);
        output.WriteMessage(Timestamp);
      }
      if (HolidayCalendar != global::Spiderrock.Protobuf.CalendarCode.Unspecified) {
        output.WriteRawTag(152, 7);
        output.WriteEnum((int) HolidayCalendar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Meta_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Meta);
      }
      if (pkey_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pkey);
      }
      if (ExType != global::Spiderrock.Protobuf.ExerciseType.Unspecified) {
        output.WriteRawTag(160, 6);
        output.WriteEnum((int) ExType);
      }
      if (ExTime != global::Spiderrock.Protobuf.ExerciseTime.Unspecified) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) ExTime);
      }
      if (TimeMetric != global::Spiderrock.Protobuf.TimeMetric.Unspecified) {
        output.WriteRawTag(176, 6);
        output.WriteEnum((int) TimeMetric);
      }
      if (PriceType != global::Spiderrock.Protobuf.CalcPriceType.Unspecified) {
        output.WriteRawTag(184, 6);
        output.WriteEnum((int) PriceType);
      }
      if (ModelType != global::Spiderrock.Protobuf.CalcModelType.Unspecified) {
        output.WriteRawTag(192, 6);
        output.WriteEnum((int) ModelType);
      }
      if (IncGreeks != global::Spiderrock.Protobuf.YesNo.Unspecified) {
        output.WriteRawTag(200, 6);
        output.WriteEnum((int) IncGreeks);
      }
      if (Vol != 0D) {
        output.WriteRawTag(209, 6);
        output.WriteDouble(Vol);
      }
      if (UPrc != 0D) {
        output.WriteRawTag(217, 6);
        output.WriteDouble(UPrc);
      }
      if (Years != 0D) {
        output.WriteRawTag(225, 6);
        output.WriteDouble(Years);
      }
      if (Sdiv != 0D) {
        output.WriteRawTag(233, 6);
        output.WriteDouble(Sdiv);
      }
      if (Rate != 0D) {
        output.WriteRawTag(241, 6);
        output.WriteDouble(Rate);
      }
      discreteDividend_.WriteTo(ref output, _repeated_discreteDividend_codec);
      if (timestamp_ != null) {
        output.WriteRawTag(146, 7);
        output.WriteMessage(Timestamp);
      }
      if (HolidayCalendar != global::Spiderrock.Protobuf.CalendarCode.Unspecified) {
        output.WriteRawTag(152, 7);
        output.WriteEnum((int) HolidayCalendar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Meta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meta);
      }
      if (pkey_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pkey);
      }
      if (ExType != global::Spiderrock.Protobuf.ExerciseType.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ExType);
      }
      if (ExTime != global::Spiderrock.Protobuf.ExerciseTime.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ExTime);
      }
      if (HolidayCalendar != global::Spiderrock.Protobuf.CalendarCode.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) HolidayCalendar);
      }
      if (TimeMetric != global::Spiderrock.Protobuf.TimeMetric.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) TimeMetric);
      }
      if (PriceType != global::Spiderrock.Protobuf.CalcPriceType.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) PriceType);
      }
      if (ModelType != global::Spiderrock.Protobuf.CalcModelType.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ModelType);
      }
      if (IncGreeks != global::Spiderrock.Protobuf.YesNo.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) IncGreeks);
      }
      if (Vol != 0D) {
        size += 2 + 8;
      }
      if (UPrc != 0D) {
        size += 2 + 8;
      }
      if (Years != 0D) {
        size += 2 + 8;
      }
      if (Sdiv != 0D) {
        size += 2 + 8;
      }
      if (Rate != 0D) {
        size += 2 + 8;
      }
      if (timestamp_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      size += discreteDividend_.CalculateSize(_repeated_discreteDividend_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OptionItemDef other) {
      if (other == null) {
        return;
      }
      if (other.Meta_ != null) {
        if (Meta_ == null) {
          Meta = new global::Spiderrock.Protobuf.MessageMetadata();
        }
        Meta.MergeFrom(other.Meta);
      }
      if (other.pkey_ != null) {
        if (pkey_ == null) {
          Pkey = new global::Spiderrock.Protobuf.OptionItemDef.Types.PKey();
        }
        Pkey.MergeFrom(other.Pkey);
      }
      if (other.ExType != global::Spiderrock.Protobuf.ExerciseType.Unspecified) {
        ExType = other.ExType;
      }
      if (other.ExTime != global::Spiderrock.Protobuf.ExerciseTime.Unspecified) {
        ExTime = other.ExTime;
      }
      if (other.HolidayCalendar != global::Spiderrock.Protobuf.CalendarCode.Unspecified) {
        HolidayCalendar = other.HolidayCalendar;
      }
      if (other.TimeMetric != global::Spiderrock.Protobuf.TimeMetric.Unspecified) {
        TimeMetric = other.TimeMetric;
      }
      if (other.PriceType != global::Spiderrock.Protobuf.CalcPriceType.Unspecified) {
        PriceType = other.PriceType;
      }
      if (other.ModelType != global::Spiderrock.Protobuf.CalcModelType.Unspecified) {
        ModelType = other.ModelType;
      }
      if (other.IncGreeks != global::Spiderrock.Protobuf.YesNo.Unspecified) {
        IncGreeks = other.IncGreeks;
      }
      if (other.Vol != 0D) {
        Vol = other.Vol;
      }
      if (other.UPrc != 0D) {
        UPrc = other.UPrc;
      }
      if (other.Years != 0D) {
        Years = other.Years;
      }
      if (other.Sdiv != 0D) {
        Sdiv = other.Sdiv;
      }
      if (other.Rate != 0D) {
        Rate = other.Rate;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      discreteDividend_.Add(other.discreteDividend_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (Meta_ == null) {
              Meta = new global::Spiderrock.Protobuf.MessageMetadata();
            }
            input.ReadMessage(Meta);
            break;
          }
          case 18: {
            if (pkey_ == null) {
              Pkey = new global::Spiderrock.Protobuf.OptionItemDef.Types.PKey();
            }
            input.ReadMessage(Pkey);
            break;
          }
          case 800: {
            ExType = (global::Spiderrock.Protobuf.ExerciseType) input.ReadEnum();
            break;
          }
          case 808: {
            ExTime = (global::Spiderrock.Protobuf.ExerciseTime) input.ReadEnum();
            break;
          }
          case 816: {
            TimeMetric = (global::Spiderrock.Protobuf.TimeMetric) input.ReadEnum();
            break;
          }
          case 824: {
            PriceType = (global::Spiderrock.Protobuf.CalcPriceType) input.ReadEnum();
            break;
          }
          case 832: {
            ModelType = (global::Spiderrock.Protobuf.CalcModelType) input.ReadEnum();
            break;
          }
          case 840: {
            IncGreeks = (global::Spiderrock.Protobuf.YesNo) input.ReadEnum();
            break;
          }
          case 849: {
            Vol = input.ReadDouble();
            break;
          }
          case 857: {
            UPrc = input.ReadDouble();
            break;
          }
          case 865: {
            Years = input.ReadDouble();
            break;
          }
          case 873: {
            Sdiv = input.ReadDouble();
            break;
          }
          case 881: {
            Rate = input.ReadDouble();
            break;
          }
          case 890: {
            discreteDividend_.AddEntriesFrom(input, _repeated_discreteDividend_codec);
            break;
          }
          case 914: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 920: {
            HolidayCalendar = (global::Spiderrock.Protobuf.CalendarCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (Meta_ == null) {
              Meta = new global::Spiderrock.Protobuf.MessageMetadata();
            }
            input.ReadMessage(Meta);
            break;
          }
          case 18: {
            if (pkey_ == null) {
              Pkey = new global::Spiderrock.Protobuf.OptionItemDef.Types.PKey();
            }
            input.ReadMessage(Pkey);
            break;
          }
          case 800: {
            ExType = (global::Spiderrock.Protobuf.ExerciseType) input.ReadEnum();
            break;
          }
          case 808: {
            ExTime = (global::Spiderrock.Protobuf.ExerciseTime) input.ReadEnum();
            break;
          }
          case 816: {
            TimeMetric = (global::Spiderrock.Protobuf.TimeMetric) input.ReadEnum();
            break;
          }
          case 824: {
            PriceType = (global::Spiderrock.Protobuf.CalcPriceType) input.ReadEnum();
            break;
          }
          case 832: {
            ModelType = (global::Spiderrock.Protobuf.CalcModelType) input.ReadEnum();
            break;
          }
          case 840: {
            IncGreeks = (global::Spiderrock.Protobuf.YesNo) input.ReadEnum();
            break;
          }
          case 849: {
            Vol = input.ReadDouble();
            break;
          }
          case 857: {
            UPrc = input.ReadDouble();
            break;
          }
          case 865: {
            Years = input.ReadDouble();
            break;
          }
          case 873: {
            Sdiv = input.ReadDouble();
            break;
          }
          case 881: {
            Rate = input.ReadDouble();
            break;
          }
          case 890: {
            discreteDividend_.AddEntriesFrom(ref input, _repeated_discreteDividend_codec);
            break;
          }
          case 914: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 920: {
            HolidayCalendar = (global::Spiderrock.Protobuf.CalendarCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OptionItemDef message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class PKey : pb::IMessage<PKey>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PKey> _parser = new pb::MessageParser<PKey>(() => new PKey());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PKey> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Spiderrock.Protobuf.OptionItemDef.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PKey() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PKey(PKey other) : this() {
          okey_ = other.okey_ != null ? other.okey_.Clone() : null;
          okeyNumber_ = other.okeyNumber_;
          basketNumber_ = other.basketNumber_;
          userName_ = other.userName_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PKey Clone() {
          return new PKey(this);
        }

        /// <summary>Field number for the "okey" field.</summary>
        public const int OkeyFieldNumber = 10;
        private global::Spiderrock.Protobuf.OptionKey okey_;
        /// <summary>
        /// can be listed or FLEX
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Spiderrock.Protobuf.OptionKey Okey {
          get { return okey_; }
          set {
            okey_ = value;
          }
        }

        /// <summary>Field number for the "okey_number" field.</summary>
        public const int OkeyNumberFieldNumber = 13;
        private int okeyNumber_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int OkeyNumber {
          get { return okeyNumber_; }
          set {
            okeyNumber_ = value;
          }
        }

        /// <summary>Field number for the "basket_number" field.</summary>
        public const int BasketNumberFieldNumber = 11;
        private long basketNumber_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long BasketNumber {
          get { return basketNumber_; }
          set {
            basketNumber_ = value;
          }
        }

        /// <summary>Field number for the "user_name" field.</summary>
        public const int UserNameFieldNumber = 12;
        private string userName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string UserName {
          get { return userName_; }
          set {
            userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as PKey);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PKey other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Okey, other.Okey)) return false;
          if (OkeyNumber != other.OkeyNumber) return false;
          if (BasketNumber != other.BasketNumber) return false;
          if (UserName != other.UserName) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (okey_ != null) hash ^= Okey.GetHashCode();
          if (OkeyNumber != 0) hash ^= OkeyNumber.GetHashCode();
          if (BasketNumber != 0L) hash ^= BasketNumber.GetHashCode();
          if (UserName.Length != 0) hash ^= UserName.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (okey_ != null) {
            output.WriteRawTag(82);
            output.WriteMessage(Okey);
          }
          if (BasketNumber != 0L) {
            output.WriteRawTag(88);
            output.WriteInt64(BasketNumber);
          }
          if (UserName.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(UserName);
          }
          if (OkeyNumber != 0) {
            output.WriteRawTag(104);
            output.WriteInt32(OkeyNumber);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (okey_ != null) {
            output.WriteRawTag(82);
            output.WriteMessage(Okey);
          }
          if (BasketNumber != 0L) {
            output.WriteRawTag(88);
            output.WriteInt64(BasketNumber);
          }
          if (UserName.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(UserName);
          }
          if (OkeyNumber != 0) {
            output.WriteRawTag(104);
            output.WriteInt32(OkeyNumber);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (okey_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Okey);
          }
          if (OkeyNumber != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(OkeyNumber);
          }
          if (BasketNumber != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(BasketNumber);
          }
          if (UserName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PKey other) {
          if (other == null) {
            return;
          }
          if (other.okey_ != null) {
            if (okey_ == null) {
              Okey = new global::Spiderrock.Protobuf.OptionKey();
            }
            Okey.MergeFrom(other.Okey);
          }
          if (other.OkeyNumber != 0) {
            OkeyNumber = other.OkeyNumber;
          }
          if (other.BasketNumber != 0L) {
            BasketNumber = other.BasketNumber;
          }
          if (other.UserName.Length != 0) {
            UserName = other.UserName;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 82: {
                if (okey_ == null) {
                  Okey = new global::Spiderrock.Protobuf.OptionKey();
                }
                input.ReadMessage(Okey);
                break;
              }
              case 88: {
                BasketNumber = input.ReadInt64();
                break;
              }
              case 98: {
                UserName = input.ReadString();
                break;
              }
              case 104: {
                OkeyNumber = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 82: {
                if (okey_ == null) {
                  Okey = new global::Spiderrock.Protobuf.OptionKey();
                }
                input.ReadMessage(Okey);
                break;
              }
              case 88: {
                BasketNumber = input.ReadInt64();
                break;
              }
              case 98: {
                UserName = input.ReadString();
                break;
              }
              case 104: {
                OkeyNumber = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class DiscreteDividend : pb::IMessage<DiscreteDividend>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<DiscreteDividend> _parser = new pb::MessageParser<DiscreteDividend>(() => new DiscreteDividend());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<DiscreteDividend> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Spiderrock.Protobuf.OptionItemDef.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DiscreteDividend() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DiscreteDividend(DiscreteDividend other) : this() {
          date_ = other.date_ != null ? other.date_.Clone() : null;
          amount_ = other.amount_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DiscreteDividend Clone() {
          return new DiscreteDividend(this);
        }

        /// <summary>Field number for the "date" field.</summary>
        public const int DateFieldNumber = 112;
        private global::Google.Protobuf.WellKnownTypes.Timestamp date_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Timestamp Date {
          get { return date_; }
          set {
            date_ = value;
          }
        }

        /// <summary>Field number for the "amount" field.</summary>
        public const int AmountFieldNumber = 113;
        private float amount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Amount {
          get { return amount_; }
          set {
            amount_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as DiscreteDividend);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(DiscreteDividend other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Date, other.Date)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Amount, other.Amount)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (date_ != null) hash ^= Date.GetHashCode();
          if (Amount != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Amount);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (date_ != null) {
            output.WriteRawTag(130, 7);
            output.WriteMessage(Date);
          }
          if (Amount != 0F) {
            output.WriteRawTag(141, 7);
            output.WriteFloat(Amount);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (date_ != null) {
            output.WriteRawTag(130, 7);
            output.WriteMessage(Date);
          }
          if (Amount != 0F) {
            output.WriteRawTag(141, 7);
            output.WriteFloat(Amount);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (date_ != null) {
            size += 2 + pb::CodedOutputStream.ComputeMessageSize(Date);
          }
          if (Amount != 0F) {
            size += 2 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(DiscreteDividend other) {
          if (other == null) {
            return;
          }
          if (other.date_ != null) {
            if (date_ == null) {
              Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            Date.MergeFrom(other.Date);
          }
          if (other.Amount != 0F) {
            Amount = other.Amount;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 898: {
                if (date_ == null) {
                  Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(Date);
                break;
              }
              case 909: {
                Amount = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 898: {
                if (date_ == null) {
                  Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(Date);
                break;
              }
              case 909: {
                Amount = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
