# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MLinkRest/PostAck.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spiderrock_common_pb2 as spiderrock__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MLinkRest/PostAck.proto\x12\x13spiderrock.protobuf\x1a\x17spiderrock_common.proto\"\xb3\x01\n\x07PostAck\x12\x33\n\x05_meta\x18\x01 \x01(\x0b\x32$.spiderrock.protobuf.MessageMetadata\x12\x10\n\x08msg_type\x18\x64 \x01(\r\x12\x0f\n\x07send_ts\x18g \x01(\x03\x12\x0c\n\x04pkey\x18j \x01(\t\x12\x32\n\x06result\x18m \x01(\x0e\x32\".spiderrock.protobuf.PostAckResult\x12\x0e\n\x06\x64\x65tail\x18p \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MLinkRest.PostAck_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POSTACK']._serialized_start=74
  _globals['_POSTACK']._serialized_end=253
# @@protoc_insertion_point(module_scope)
