# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MLinkWs/MLinkStreamCheckPt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spiderrock_common_pb2 as spiderrock__common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n MLinkWs/MLinkStreamCheckPt.proto\x12\x13spiderrock.protobuf\x1a\x17spiderrock_common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n\x12MLinkStreamCheckPt\x12\x33\n\x05_meta\x18\x01 \x01(\x0b\x32$.spiderrock.protobuf.MessageMetadata\x12\x12\n\nsession_iD\x18\x64 \x01(\x05\x12\x10\n\x08query_iD\x18g \x01(\x03\x12\x11\n\tsignal_iD\x18j \x01(\x03\x12\x34\n\x05state\x18m \x01(\x0e\x32%.spiderrock.protobuf.MLinkStreamState\x12\x0e\n\x06\x64\x65tail\x18p \x01(\t\x12\x14\n\x0chighwater_ts\x18s \x01(\x03\x12\x16\n\x0enum_bytes_sent\x18v \x01(\x03\x12\x19\n\x11num_messages_sent\x18y \x01(\x05\x12\x14\n\x0cwait_elapsed\x18| \x01(\x01\x12\x15\n\rquery_elapsed\x18\x7f \x01(\x01\x12\x18\n\x0ftry_fwd_elapsed\x18\x82\x01 \x01(\x01\x12\x15\n\x0csend_elapsed\x18\x85\x01 \x01(\x01\x12\x16\n\rflush_elapsed\x18\x88\x01 \x01(\x01\x12.\n\ttimestamp\x18\x8b\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MLinkWs.MLinkStreamCheckPt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MLINKSTREAMCHECKPT']._serialized_start=116
  _globals['_MLINKSTREAMCHECKPT']._serialized_end=555
# @@protoc_insertion_point(module_scope)
