# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OptAnalytics/LiveImpliedQuoteDisp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spiderrock_common_pb2 as spiderrock__common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'OptAnalytics/LiveImpliedQuoteDisp.proto\x12\x13spiderrock.protobuf\x1a\x17spiderrock_common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x06\n\x14LiveImpliedQuoteDisp\x12\x33\n\x05_meta\x18\x01 \x01(\x0b\x32$.spiderrock.protobuf.MessageMetadata\x12<\n\x04pkey\x18\x02 \x01(\x0b\x32..spiderrock.protobuf.LiveImpliedQuoteDisp.PKey\x12.\n\x06ticker\x18\x64 \x01(\x0b\x32\x1e.spiderrock.protobuf.TickerKey\x12\r\n\x05u_prc\x18\x65 \x01(\x02\x12\x12\n\ncls_bid_iv\x18\x66 \x01(\x02\x12\x12\n\ncls_ask_iv\x18g \x01(\x02\x12\x13\n\x0b\x63ls_mid_vol\x18h \x01(\x02\x12\x12\n\ncls_sr_vol\x18i \x01(\x02\x12\x10\n\x08o_bid_iv\x18j \x01(\x02\x12\x10\n\x08o_ask_iv\x18k \x01(\x02\x12\x0f\n\x07mid_vol\x18l \x01(\x02\x12\r\n\x05s_vol\x18m \x01(\x02\x12\r\n\x05s_prc\x18n \x01(\x02\x12\x0f\n\x07prt_prc\x18o \x01(\x02\x12\x10\n\x08surf_vol\x18p \x01(\x02\x12\x12\n\nprt_volume\x18q \x01(\x05\x12\x0e\n\x06prt_iV\x18r \x01(\x02\x12\n\n\x02\x64\x65\x18s \x01(\x02\x12\n\n\x02ga\x18t \x01(\x02\x12\n\n\x02th\x18u \x01(\x02\x12\n\n\x02ve\x18v \x01(\x02\x12\n\n\x02va\x18w \x01(\x02\x12\n\n\x02vo\x18x \x01(\x02\x12\n\n\x02ro\x18y \x01(\x02\x12\n\n\x02ph\x18z \x01(\x02\x12\x38\n\x08\x63\x61lc_err\x18{ \x01(\x0e\x32&.spiderrock.protobuf.ImpliedQuoteError\x12\x34\n\x0b\x63\x61lc_source\x18| \x01(\x0e\x32\x1f.spiderrock.protobuf.CalcSource\x12\x15\n\rsrc_timestamp\x18} \x01(\x03\x12\x15\n\rnet_timestamp\x18~ \x01(\x03\x12-\n\ttimestamp\x18\x7f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x34\n\x04PKey\x12,\n\x04okey\x18\n \x01(\x0b\x32\x1e.spiderrock.protobuf.OptionKeyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OptAnalytics.LiveImpliedQuoteDisp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LIVEIMPLIEDQUOTEDISP']._serialized_start=123
  _globals['_LIVEIMPLIEDQUOTEDISP']._serialized_end=913
  _globals['_LIVEIMPLIEDQUOTEDISP_PKEY']._serialized_start=861
  _globals['_LIVEIMPLIEDQUOTEDISP_PKEY']._serialized_end=913
# @@protoc_insertion_point(module_scope)
