# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OptionDefinition/OpraPrintType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spiderrock_common_pb2 as spiderrock__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$OptionDefinition/OpraPrintType.proto\x12\x13spiderrock.protobuf\x1a\x17spiderrock_common.proto\"\x84\x02\n\rOpraPrintType\x12\x33\n\x05_meta\x18\x01 \x01(\x0b\x32$.spiderrock.protobuf.MessageMetadata\x12\x35\n\x04pkey\x18\x02 \x01(\x0b\x32\'.spiderrock.protobuf.OpraPrintType.PKey\x12\x17\n\x0fprint_type_char\x18\x64 \x01(\t\x12\x12\n\nprint_code\x18g \x01(\t\x12\x19\n\x11print_code_string\x18j \x01(\t\x12\x1e\n\x16print_code_description\x18m \x01(\t\x1a\x1f\n\x04PKey\x12\x17\n\x0fopra_print_type\x18\n \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OptionDefinition.OpraPrintType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OPRAPRINTTYPE']._serialized_start=87
  _globals['_OPRAPRINTTYPE']._serialized_end=347
  _globals['_OPRAPRINTTYPE_PKEY']._serialized_start=316
  _globals['_OPRAPRINTTYPE_PKEY']._serialized_end=347
# @@protoc_insertion_point(module_scope)
