name: Build C#

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to run against'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      working-directory: SpiderStream/_csharp
      run: dotnet restore
    - name: Build
      working-directory: SpiderStream/_csharp
      run: dotnet build --no-restore
    - name: Test
      working-directory: SpiderStream/_csharp
      run: dotnet test --no-build --verbosity normal
