name: Build C++ (Linux)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to run against'
        required: true
        default: 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libwebsocketpp-dev libboost-all-dev
    - name: Build libSRDF
      working-directory: SpiderStream/_c++/libSpiderStream
      run: make
    - name: Build ServerExample
      working-directory: SpiderStream/_c++/ServerExample
      run: make
